// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string toiletName = 1;</code>
   */
  java.lang.String getToiletName();
  /**
   * <code>string toiletName = 1;</code>
   */
  com.google.protobuf.ByteString
      getToiletNameBytes();

  /**
   * <code>string exceededVisitsLimit = 2;</code>
   */
  java.lang.String getExceededVisitsLimit();
  /**
   * <code>string exceededVisitsLimit = 2;</code>
   */
  com.google.protobuf.ByteString
      getExceededVisitsLimitBytes();

  /**
   * <code>int32 numberOfExceededVisits = 3;</code>
   */
  int getNumberOfExceededVisits();
}
