// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 input = 1;</code>
   */
  int getInput();

  /**
   * <code>.service3.ErrorCode error_code = 2;</code>
   */
  int getErrorCodeValue();
  /**
   * <code>.service3.ErrorCode error_code = 2;</code>
   */
  ds.service3.ErrorCode getErrorCode();
}
