// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

/**
 * Protobuf type {@code service3.ToiletVisitsResponse}
 */
public  final class ToiletVisitsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.ToiletVisitsResponse)
    ToiletVisitsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ToiletVisitsResponse.newBuilder() to construct.
  private ToiletVisitsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ToiletVisitsResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ToiletVisitsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ds.service3.Toilet.Builder subBuilder = null;
            if (toilet_ != null) {
              subBuilder = toilet_.toBuilder();
            }
            toilet_ = input.readMessage(ds.service3.Toilet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(toilet_);
              toilet_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.service3.Service3Impl.internal_static_service3_ToiletVisitsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.service3.Service3Impl.internal_static_service3_ToiletVisitsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.service3.ToiletVisitsResponse.class, ds.service3.ToiletVisitsResponse.Builder.class);
  }

  public static final int TOILET_FIELD_NUMBER = 1;
  private ds.service3.Toilet toilet_;
  /**
   * <code>.service3.Toilet toilet = 1;</code>
   */
  public boolean hasToilet() {
    return toilet_ != null;
  }
  /**
   * <code>.service3.Toilet toilet = 1;</code>
   */
  public ds.service3.Toilet getToilet() {
    return toilet_ == null ? ds.service3.Toilet.getDefaultInstance() : toilet_;
  }
  /**
   * <code>.service3.Toilet toilet = 1;</code>
   */
  public ds.service3.ToiletOrBuilder getToiletOrBuilder() {
    return getToilet();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (toilet_ != null) {
      output.writeMessage(1, getToilet());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (toilet_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getToilet());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.service3.ToiletVisitsResponse)) {
      return super.equals(obj);
    }
    ds.service3.ToiletVisitsResponse other = (ds.service3.ToiletVisitsResponse) obj;

    boolean result = true;
    result = result && (hasToilet() == other.hasToilet());
    if (hasToilet()) {
      result = result && getToilet()
          .equals(other.getToilet());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasToilet()) {
      hash = (37 * hash) + TOILET_FIELD_NUMBER;
      hash = (53 * hash) + getToilet().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.service3.ToiletVisitsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service3.ToiletVisitsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.service3.ToiletVisitsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service3.ToiletVisitsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.service3.ToiletVisitsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3.ToiletVisitsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.ToiletVisitsResponse)
      ds.service3.ToiletVisitsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service3.Service3Impl.internal_static_service3_ToiletVisitsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service3.Service3Impl.internal_static_service3_ToiletVisitsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service3.ToiletVisitsResponse.class, ds.service3.ToiletVisitsResponse.Builder.class);
    }

    // Construct using ds.service3.ToiletVisitsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (toiletBuilder_ == null) {
        toilet_ = null;
      } else {
        toilet_ = null;
        toiletBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.service3.Service3Impl.internal_static_service3_ToiletVisitsResponse_descriptor;
    }

    @java.lang.Override
    public ds.service3.ToiletVisitsResponse getDefaultInstanceForType() {
      return ds.service3.ToiletVisitsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.service3.ToiletVisitsResponse build() {
      ds.service3.ToiletVisitsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.service3.ToiletVisitsResponse buildPartial() {
      ds.service3.ToiletVisitsResponse result = new ds.service3.ToiletVisitsResponse(this);
      if (toiletBuilder_ == null) {
        result.toilet_ = toilet_;
      } else {
        result.toilet_ = toiletBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.service3.ToiletVisitsResponse) {
        return mergeFrom((ds.service3.ToiletVisitsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.service3.ToiletVisitsResponse other) {
      if (other == ds.service3.ToiletVisitsResponse.getDefaultInstance()) return this;
      if (other.hasToilet()) {
        mergeToilet(other.getToilet());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.service3.ToiletVisitsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.service3.ToiletVisitsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ds.service3.Toilet toilet_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.service3.Toilet, ds.service3.Toilet.Builder, ds.service3.ToiletOrBuilder> toiletBuilder_;
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public boolean hasToilet() {
      return toiletBuilder_ != null || toilet_ != null;
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public ds.service3.Toilet getToilet() {
      if (toiletBuilder_ == null) {
        return toilet_ == null ? ds.service3.Toilet.getDefaultInstance() : toilet_;
      } else {
        return toiletBuilder_.getMessage();
      }
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public Builder setToilet(ds.service3.Toilet value) {
      if (toiletBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toilet_ = value;
        onChanged();
      } else {
        toiletBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public Builder setToilet(
        ds.service3.Toilet.Builder builderForValue) {
      if (toiletBuilder_ == null) {
        toilet_ = builderForValue.build();
        onChanged();
      } else {
        toiletBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public Builder mergeToilet(ds.service3.Toilet value) {
      if (toiletBuilder_ == null) {
        if (toilet_ != null) {
          toilet_ =
            ds.service3.Toilet.newBuilder(toilet_).mergeFrom(value).buildPartial();
        } else {
          toilet_ = value;
        }
        onChanged();
      } else {
        toiletBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public Builder clearToilet() {
      if (toiletBuilder_ == null) {
        toilet_ = null;
        onChanged();
      } else {
        toilet_ = null;
        toiletBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public ds.service3.Toilet.Builder getToiletBuilder() {
      
      onChanged();
      return getToiletFieldBuilder().getBuilder();
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    public ds.service3.ToiletOrBuilder getToiletOrBuilder() {
      if (toiletBuilder_ != null) {
        return toiletBuilder_.getMessageOrBuilder();
      } else {
        return toilet_ == null ?
            ds.service3.Toilet.getDefaultInstance() : toilet_;
      }
    }
    /**
     * <code>.service3.Toilet toilet = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.service3.Toilet, ds.service3.Toilet.Builder, ds.service3.ToiletOrBuilder> 
        getToiletFieldBuilder() {
      if (toiletBuilder_ == null) {
        toiletBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ds.service3.Toilet, ds.service3.Toilet.Builder, ds.service3.ToiletOrBuilder>(
                getToilet(),
                getParentForChildren(),
                isClean());
        toilet_ = null;
      }
      return toiletBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.ToiletVisitsResponse)
  }

  // @@protoc_insertion_point(class_scope:service3.ToiletVisitsResponse)
  private static final ds.service3.ToiletVisitsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.service3.ToiletVisitsResponse();
  }

  public static ds.service3.ToiletVisitsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ToiletVisitsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ToiletVisitsResponse>() {
    @java.lang.Override
    public ToiletVisitsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ToiletVisitsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ToiletVisitsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ToiletVisitsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.service3.ToiletVisitsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

