// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface ToiletOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.Toilet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberOfVisits = 1;</code>
   */
  int getNumberOfVisits();

  /**
   * <code>string toiletName = 2;</code>
   */
  java.lang.String getToiletName();
  /**
   * <code>string toiletName = 2;</code>
   */
  com.google.protobuf.ByteString
      getToiletNameBytes();
}
