// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface ToiletVisitsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.ToiletVisitsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string toiletLastEnterDateAndTime = 1;</code>
   */
  java.lang.String getToiletLastEnterDateAndTime();
  /**
   * <code>string toiletLastEnterDateAndTime = 1;</code>
   */
  com.google.protobuf.ByteString
      getToiletLastEnterDateAndTimeBytes();

  /**
   * <code>.service3.Toilet toilet = 2;</code>
   */
  boolean hasToilet();
  /**
   * <code>.service3.Toilet toilet = 2;</code>
   */
  ds.service3.Toilet getToilet();
  /**
   * <code>.service3.Toilet toilet = 2;</code>
   */
  ds.service3.ToiletOrBuilder getToiletOrBuilder();
}
