// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface ToiletVisitsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.ToiletVisitsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service3.Toilet toilet = 1;</code>
   */
  boolean hasToilet();
  /**
   * <code>.service3.Toilet toilet = 1;</code>
   */
  ds.service3.Toilet getToilet();
  /**
   * <code>.service3.Toilet toilet = 1;</code>
   */
  ds.service3.ToiletOrBuilder getToiletOrBuilder();
}
