// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface ChairHeightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ChairHeightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service2.Chair chair = 1;</code>
   */
  boolean hasChair();
  /**
   * <code>.service2.Chair chair = 1;</code>
   */
  ds.service2.Chair getChair();
  /**
   * <code>.service2.Chair chair = 1;</code>
   */
  ds.service2.ChairOrBuilder getChairOrBuilder();

  /**
   * <code>.service2.ChairHeightRequest.ChairOperation chairOperation = 2;</code>
   */
  int getChairOperationValue();
  /**
   * <code>.service2.ChairHeightRequest.ChairOperation chairOperation = 2;</code>
   */
  ds.service2.ChairHeightRequest.ChairOperation getChairOperation();
}
