// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface ChairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.Chair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 chairHeight = 1;</code>
   */
  int getChairHeight();

  /**
   * <code>int32 deskNumber = 2;</code>
   */
  int getDeskNumber();

  /**
   * <code>string roomName = 3;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 3;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();
}
