// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface ChairHeightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ChairHeightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service2.Chair chair = 1;</code>
   */
  boolean hasChair();
  /**
   * <code>.service2.Chair chair = 1;</code>
   */
  ds.service2.Chair getChair();
  /**
   * <code>.service2.Chair chair = 1;</code>
   */
  ds.service2.ChairOrBuilder getChairOrBuilder();

  /**
   * <code>bool isHeightAdjusted = 2;</code>
   */
  boolean getIsHeightAdjusted();
}
