// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface DeskDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.DeskDetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deskNumber = 1;</code>
   */
  int getDeskNumber();

  /**
   * <code>string roomName = 2;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>int32 deskHeight = 3;</code>
   */
  int getDeskHeight();

  /**
   * <code>.service2.DeskDetailsRequest.Operation operation = 4;</code>
   */
  int getOperationValue();
  /**
   * <code>.service2.DeskDetailsRequest.Operation operation = 4;</code>
   */
  ds.service2.DeskDetailsRequest.Operation getOperation();
}
