// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface DeskAdjustedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.DeskAdjustedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deskHeight = 1;</code>
   */
  int getDeskHeight();

  /**
   * <code>bool isHeightAdjusted = 2;</code>
   */
  boolean getIsHeightAdjusted();
}
