// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_DeskDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_DeskDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_DeskAdjustedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_DeskAdjustedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\"\260\001\n\022DeskDetai" +
      "lsRequest\022\022\n\ndeskNumber\030\001 \001(\005\022\020\n\010roomNam" +
      "e\030\002 \001(\t\022\022\n\ndeskHeight\030\003 \001(\005\0229\n\toperation" +
      "\030\004 \001(\0162&.service2.DeskDetailsRequest.Ope" +
      "ration\"%\n\tOperation\022\n\n\006DESKUP\020\000\022\014\n\010DESKD" +
      "OWN\020\001\"D\n\024DeskAdjustedResponse\022\022\n\ndeskHei" +
      "ght\030\001 \001(\005\022\030\n\020isHeightAdjusted\030\002 \001(\0102_\n\010S" +
      "ervice2\022S\n\021DeskStatusInquiry\022\034.service2." +
      "DeskDetailsRequest\032\036.service2.DeskAdjust" +
      "edResponse\"\000B\035\n\013ds.service2B\014Service2Imp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_DeskDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_DeskDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_DeskDetailsRequest_descriptor,
        new java.lang.String[] { "DeskNumber", "RoomName", "DeskHeight", "Operation", });
    internal_static_service2_DeskAdjustedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_DeskAdjustedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_DeskAdjustedResponse_descriptor,
        new java.lang.String[] { "DeskHeight", "IsHeightAdjusted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
