// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface AcknowledgedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Acknowledged)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string acknowledgment = 1;</code>
   */
  java.lang.String getAcknowledgment();
  /**
   * <code>string acknowledgment = 1;</code>
   */
  com.google.protobuf.ByteString
      getAcknowledgmentBytes();
}
