// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface AdjustHVACOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AdjustHVAC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double humidityDifference = 1;</code>
   */
  double getHumidityDifference();

  /**
   * <code>double tempDifference = 2;</code>
   */
  double getTempDifference();
}
