// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

/**
 * Protobuf type {@code service1.AdjustHVAC}
 */
public  final class AdjustHVAC extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.AdjustHVAC)
    AdjustHVACOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdjustHVAC.newBuilder() to construct.
  private AdjustHVAC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdjustHVAC() {
    humidityDifference_ = 0D;
    tempDifference_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdjustHVAC(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            humidityDifference_ = input.readDouble();
            break;
          }
          case 17: {

            tempDifference_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.service1.Service1Impl.internal_static_service1_AdjustHVAC_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.service1.Service1Impl.internal_static_service1_AdjustHVAC_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.service1.AdjustHVAC.class, ds.service1.AdjustHVAC.Builder.class);
  }

  public static final int HUMIDITYDIFFERENCE_FIELD_NUMBER = 1;
  private double humidityDifference_;
  /**
   * <code>double humidityDifference = 1;</code>
   */
  public double getHumidityDifference() {
    return humidityDifference_;
  }

  public static final int TEMPDIFFERENCE_FIELD_NUMBER = 2;
  private double tempDifference_;
  /**
   * <code>double tempDifference = 2;</code>
   */
  public double getTempDifference() {
    return tempDifference_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (humidityDifference_ != 0D) {
      output.writeDouble(1, humidityDifference_);
    }
    if (tempDifference_ != 0D) {
      output.writeDouble(2, tempDifference_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (humidityDifference_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, humidityDifference_);
    }
    if (tempDifference_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, tempDifference_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.service1.AdjustHVAC)) {
      return super.equals(obj);
    }
    ds.service1.AdjustHVAC other = (ds.service1.AdjustHVAC) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getHumidityDifference())
        == java.lang.Double.doubleToLongBits(
            other.getHumidityDifference()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTempDifference())
        == java.lang.Double.doubleToLongBits(
            other.getTempDifference()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HUMIDITYDIFFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHumidityDifference()));
    hash = (37 * hash) + TEMPDIFFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTempDifference()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.service1.AdjustHVAC parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.AdjustHVAC parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.AdjustHVAC parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.AdjustHVAC parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.AdjustHVAC parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.service1.AdjustHVAC parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.service1.AdjustHVAC parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service1.AdjustHVAC parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service1.AdjustHVAC parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.service1.AdjustHVAC parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.service1.AdjustHVAC parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.service1.AdjustHVAC parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.service1.AdjustHVAC prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.AdjustHVAC}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.AdjustHVAC)
      ds.service1.AdjustHVACOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service1.Service1Impl.internal_static_service1_AdjustHVAC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service1.Service1Impl.internal_static_service1_AdjustHVAC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service1.AdjustHVAC.class, ds.service1.AdjustHVAC.Builder.class);
    }

    // Construct using ds.service1.AdjustHVAC.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      humidityDifference_ = 0D;

      tempDifference_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.service1.Service1Impl.internal_static_service1_AdjustHVAC_descriptor;
    }

    @java.lang.Override
    public ds.service1.AdjustHVAC getDefaultInstanceForType() {
      return ds.service1.AdjustHVAC.getDefaultInstance();
    }

    @java.lang.Override
    public ds.service1.AdjustHVAC build() {
      ds.service1.AdjustHVAC result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.service1.AdjustHVAC buildPartial() {
      ds.service1.AdjustHVAC result = new ds.service1.AdjustHVAC(this);
      result.humidityDifference_ = humidityDifference_;
      result.tempDifference_ = tempDifference_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.service1.AdjustHVAC) {
        return mergeFrom((ds.service1.AdjustHVAC)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.service1.AdjustHVAC other) {
      if (other == ds.service1.AdjustHVAC.getDefaultInstance()) return this;
      if (other.getHumidityDifference() != 0D) {
        setHumidityDifference(other.getHumidityDifference());
      }
      if (other.getTempDifference() != 0D) {
        setTempDifference(other.getTempDifference());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.service1.AdjustHVAC parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.service1.AdjustHVAC) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double humidityDifference_ ;
    /**
     * <code>double humidityDifference = 1;</code>
     */
    public double getHumidityDifference() {
      return humidityDifference_;
    }
    /**
     * <code>double humidityDifference = 1;</code>
     */
    public Builder setHumidityDifference(double value) {
      
      humidityDifference_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double humidityDifference = 1;</code>
     */
    public Builder clearHumidityDifference() {
      
      humidityDifference_ = 0D;
      onChanged();
      return this;
    }

    private double tempDifference_ ;
    /**
     * <code>double tempDifference = 2;</code>
     */
    public double getTempDifference() {
      return tempDifference_;
    }
    /**
     * <code>double tempDifference = 2;</code>
     */
    public Builder setTempDifference(double value) {
      
      tempDifference_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double tempDifference = 2;</code>
     */
    public Builder clearTempDifference() {
      
      tempDifference_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.AdjustHVAC)
  }

  // @@protoc_insertion_point(class_scope:service1.AdjustHVAC)
  private static final ds.service1.AdjustHVAC DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.service1.AdjustHVAC();
  }

  public static ds.service1.AdjustHVAC getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdjustHVAC>
      PARSER = new com.google.protobuf.AbstractParser<AdjustHVAC>() {
    @java.lang.Override
    public AdjustHVAC parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdjustHVAC(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdjustHVAC> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdjustHVAC> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.service1.AdjustHVAC getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

