// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface AdjustHVACOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AdjustHVAC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool adjustHumidity = 1;</code>
   */
  boolean getAdjustHumidity();

  /**
   * <code>bool adjustTemp = 2;</code>
   */
  boolean getAdjustTemp();

  /**
   * <code>int32 humidityDifference = 3;</code>
   */
  int getHumidityDifference();

  /**
   * <code>int32 tempDifference = 4;</code>
   */
  int getTempDifference();
}
