// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface ConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Confirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
