// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface DesiredRoomConditionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.DesiredRoomConditions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomName = 1;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>double desiredHumidity = 2;</code>
   */
  double getDesiredHumidity();

  /**
   * <code>double desiredTempInCelcius = 3;</code>
   */
  double getDesiredTempInCelcius();
}
