// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface RoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Room)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberOfPeople = 1;</code>
   */
  int getNumberOfPeople();

  /**
   * <code>string roomName = 2;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>float humidity = 3;</code>
   */
  float getHumidity();

  /**
   * <code>float tempInCelcius = 4;</code>
   */
  float getTempInCelcius();
}
