// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_DesiredRoomConditions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_DesiredRoomConditions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Confirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Confirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_CurrentRoomConditions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_CurrentRoomConditions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Acknowledged_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Acknowledged_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Room_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Room_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AdjustHVAC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AdjustHVAC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"`\n\025DesiredRoo" +
      "mConditions\022\020\n\010roomName\030\001 \001(\t\022\027\n\017desired" +
      "Humidity\030\002 \001(\002\022\034\n\024desiredTempInCelcius\030\003" +
      " \001(\002\"$\n\014Confirmation\022\024\n\014confirmation\030\001 \001" +
      "(\t\"R\n\025CurrentRoomConditions\022\020\n\010roomName\030" +
      "\001 \001(\t\022\020\n\010humidity\030\002 \001(\002\022\025\n\rtempInCelcius" +
      "\030\003 \001(\002\"&\n\014Acknowledged\022\026\n\016acknowledgment" +
      "\030\001 \001(\t\"\030\n\004Room\022\020\n\010roomName\030\001 \001(\t\"@\n\nAdju" +
      "stHVAC\022\032\n\022humidityDifference\030\001 \001(\005\022\026\n\016te" +
      "mpDifference\030\002 \001(\0052\336\001\n\010Service1\022O\n\022desir" +
      "edSettingHVAC\022\037.service1.DesiredRoomCond" +
      "itions\032\026.service1.Confirmation\"\000\022I\n\nHVAC" +
      "status\022\037.service1.CurrentRoomConditions\032" +
      "\026.service1.Acknowledged\"\000(\001\0226\n\nRoomStatu" +
      "s\022\016.service1.Room\032\024.service1.AdjustHVAC\"" +
      "\0000\001B\035\n\013ds.service1B\014Service1ImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_DesiredRoomConditions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_DesiredRoomConditions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_DesiredRoomConditions_descriptor,
        new java.lang.String[] { "RoomName", "DesiredHumidity", "DesiredTempInCelcius", });
    internal_static_service1_Confirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_Confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Confirmation_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_service1_CurrentRoomConditions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_CurrentRoomConditions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_CurrentRoomConditions_descriptor,
        new java.lang.String[] { "RoomName", "Humidity", "TempInCelcius", });
    internal_static_service1_Acknowledged_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_Acknowledged_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Acknowledged_descriptor,
        new java.lang.String[] { "Acknowledgment", });
    internal_static_service1_Room_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_Room_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Room_descriptor,
        new java.lang.String[] { "RoomName", });
    internal_static_service1_AdjustHVAC_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_AdjustHVAC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AdjustHVAC_descriptor,
        new java.lang.String[] { "HumidityDifference", "TempDifference", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
