// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_NumberRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_NumberRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_NumberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_NumberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_SumResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_SumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"-\n\rNumberRequ" +
      "est\022\014\n\004text\030\001 \001(\t\022\016\n\006number\030\002 \001(\005\".\n\016Num" +
      "berResponse\022\014\n\004text\030\001 \001(\t\022\016\n\006number\030\002 \001(" +
      "\005\"9\n\013SumResponse\022\014\n\004text\030\001 \001(\t\022\016\n\006number" +
      "\030\002 \001(\005\022\014\n\004fnum\030\003 \001(\0022\213\002\n\010Service1\022>\n\007squ" +
      "ared\022\027.service1.NumberRequest\032\030.service1" +
      ".NumberResponse\"\000\0229\n\003sum\022\027.service1.Numb" +
      "erRequest\032\025.service1.SumResponse\"\000(\001\022B\n\t" +
      "fibonacci\022\027.service1.NumberRequest\032\030.ser" +
      "vice1.NumberResponse\"\0000\001\022@\n\005total\022\027.serv" +
      "ice1.NumberRequest\032\030.service1.NumberResp" +
      "onse\"\000(\0010\001B\035\n\013ds.service1B\014Service1ImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_NumberRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_NumberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_NumberRequest_descriptor,
        new java.lang.String[] { "Text", "Number", });
    internal_static_service1_NumberResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_NumberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_NumberResponse_descriptor,
        new java.lang.String[] { "Text", "Number", });
    internal_static_service1_SumResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_SumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_SumResponse_descriptor,
        new java.lang.String[] { "Text", "Number", "Fnum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
